// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $assistants_id_middleware from "./routes/assistants/[id]/_middleware.ts";
import * as $assistants_id_edit from "./routes/assistants/[id]/edit.tsx";
import * as $assistants_id_index from "./routes/assistants/[id]/index.tsx";
import * as $assistants_id_upload from "./routes/assistants/[id]/upload.tsx";
import * as $assistants_layout from "./routes/assistants/_layout.tsx";
import * as $assistants_create from "./routes/assistants/create.tsx";
import * as $assistants_index from "./routes/assistants/index.tsx";
import * as $chats_jid_middleware from "./routes/chats/[jid]/_middleware.ts";
import * as $chats_jid_edit from "./routes/chats/[jid]/edit.tsx";
import * as $chats_jid_index from "./routes/chats/[jid]/index.tsx";
import * as $chats_layout from "./routes/chats/_layout.tsx";
import * as $chats_create from "./routes/chats/create.tsx";
import * as $chats_index from "./routes/chats/index.tsx";
import * as $function_tools_name_middleware from "./routes/function-tools/[name]/_middleware.ts";
import * as $function_tools_name_edit from "./routes/function-tools/[name]/edit.tsx";
import * as $function_tools_name_index from "./routes/function-tools/[name]/index.tsx";
import * as $function_tools_layout from "./routes/function-tools/_layout.tsx";
import * as $function_tools_create from "./routes/function-tools/create.tsx";
import * as $function_tools_index from "./routes/function-tools/index.tsx";
import * as $function_tools_playground from "./routes/function-tools/playground.tsx";
import * as $index from "./routes/index.tsx";
import * as $CodeEditor from "./islands/CodeEditor.tsx";
import * as $DeleteButton from "./islands/DeleteButton.tsx";
import * as $ModalDialog from "./islands/ModalDialog.tsx";
import * as $TryRun from "./islands/TryRun.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/assistants/[id]/_middleware.ts": $assistants_id_middleware,
    "./routes/assistants/[id]/edit.tsx": $assistants_id_edit,
    "./routes/assistants/[id]/index.tsx": $assistants_id_index,
    "./routes/assistants/[id]/upload.tsx": $assistants_id_upload,
    "./routes/assistants/_layout.tsx": $assistants_layout,
    "./routes/assistants/create.tsx": $assistants_create,
    "./routes/assistants/index.tsx": $assistants_index,
    "./routes/chats/[jid]/_middleware.ts": $chats_jid_middleware,
    "./routes/chats/[jid]/edit.tsx": $chats_jid_edit,
    "./routes/chats/[jid]/index.tsx": $chats_jid_index,
    "./routes/chats/_layout.tsx": $chats_layout,
    "./routes/chats/create.tsx": $chats_create,
    "./routes/chats/index.tsx": $chats_index,
    "./routes/function-tools/[name]/_middleware.ts":
      $function_tools_name_middleware,
    "./routes/function-tools/[name]/edit.tsx": $function_tools_name_edit,
    "./routes/function-tools/[name]/index.tsx": $function_tools_name_index,
    "./routes/function-tools/_layout.tsx": $function_tools_layout,
    "./routes/function-tools/create.tsx": $function_tools_create,
    "./routes/function-tools/index.tsx": $function_tools_index,
    "./routes/function-tools/playground.tsx": $function_tools_playground,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CodeEditor.tsx": $CodeEditor,
    "./islands/DeleteButton.tsx": $DeleteButton,
    "./islands/ModalDialog.tsx": $ModalDialog,
    "./islands/TryRun.tsx": $TryRun,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
